name: Dump
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7     # ローカルアクションの呼び出し前にチェックアウト
      - uses: ./.github/actions/dump/
        id: dump                      # 出力値参照のためステップIDを定義
        with:
          enable-context: 'true'
      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }}
